/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   error-message.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.

/**
 * `<error-message>` A standarized error information
 *
 * ### Example
 * ```
 * <error-message icon="warning">
 *   <p>This is a warning!</p>
 * </error-message>
 * ```
 *
 * ### Styling
 * `<error-message>` provides the following custom properties and mixins for styling:
 *
 * Custom property | Description | Default
 * ----------------|-------------|----------
 * `--error-message-icon-color` | Fill color of the icon. Only if an icon is a SVG icon. | `rgba(0, 0, 0, 0.56)`
 * `--error-message-color` | Color of the message text. | `--google-red-500`
 * `--error-message-background-color` | Background color of the component | ``
 * `--arc-font-subhead-font-size` | Font size of the message (theme item) | ``
 * `--arc-font-subhead-font-weight` | Font weigth of the message (theme item) | ``
 * `--arc-font-subhead-line-height` | Font line height of the message (theme item) | ``
 */
declare class ErrorMessage extends PolymerElement {

  /**
   * An icon to render.
   */
  icon: string|null|undefined;
}

declare global {

  interface HTMLElementTagNameMap {
    "error-message": ErrorMessage;
  }
}

export {};
